### ISSUE TITLE
type errors when using lodash libdef from https://github.com/flowtype/flow-typed

### ISSUE THREAD

**Issue by soenkehahn** [andreypopp/validated#12]
I was trying to use `validated` in a project that also uses `lodash` and pulls in libdefs for `lodash` from https://github.com/flowtype/flow-typed using `flow-typed`. Unfortunately, the `schema.js.flow` file from `validated` also uses `lodash` and is then -- in my project -- type-checked against that same `lodash` libdef. Which results in type-errors. It seems that `validated` doesn't use a libdef for `lodash` (or uses an older version).

I've created this script to reproduce the issue: https://gist.github.com/98d5c35f8d789db2a252c720151ae03f

I think ideally, `flow` would only type-check the dependency `validated` against whatever libdefs are used when developing `validated` itself, if any. Is it possible to somehow tell `flow` to do that?

Alternatively, `validated` could be made work with the current `lodash` libdef. The simplest way to do that, is to just add type annotations of `any` to all imports from `lodash`.

(I'd probably be willing to put up a PR if we settle on a solution.)

**Comment by andreypopp** [comment]
I think the best way for validated would be to get rid of lodash, what do
you think?

**Comment by soenkehahn** [comment]
If that's easily possible, I think that's a good idea, yes. Maybe I'll give that a try and then I'll report back here.

**Comment by andreypopp** [comment]
Ok 👌

**Comment by andreypopp** [comment]
Released in 1.1.0.
