### ISSUE TITLE
Does not work with the new flow strict mode

### ISSUE THREAD

**Issue by Alxandr** [andreypopp/validated#18]
I get 3 errors with the new flow strict mode about parameters being re-assigned (flow now treats them as consts).

**[Update]**  
Actually, I get a few more errors. One of them is an array index issue.

![image](https://user-images.githubusercontent.com/112334/35145329-bcd6c52c-fd07-11e7-90f6-984c90440488.png)

**Comment by andreypopp** [comment]
Thanks for the fix!
