### ISSUE TITLE
Type inference with sequence

### ISSUE THREAD

**Issue by mkatrenik** [andreypopp/validated#4]
Flow can correctly infer:
```
 ... s.sequence(s.number)
 ... s.sequence(new PointNode())
```

but not object or partialObject:
```
 ... s.sequence(s.object({ foo: s.number }))
```

**Comment by andreypopp** [comment]
Hm... just tried 
<img width="394" alt="screenshot 2016-10-04 23 43 17" src="https://cloud.githubusercontent.com/assets/30594/19091701/620eabc6-8a8c-11e6-8de4-be5928249cfc.png">
and it seems to work.

**Comment by mkatrenik** [comment]
You are right, I was confused by IDE's tooltip which just shows `any`, but it works.

**Comment by andreypopp** [comment]
Yeah, flow IDe tooling could be better. Probably worth reporting to flow team.
