### ISSUE TITLE
the published npm package does not contain the .flowconfig file

### ISSUE THREAD

**Issue by vicapow** [andreypopp/validated#5]
To reproduce:

    npm install validated --save
    ls -al node_modules/validated/

````
.            README.md    lib          package.json schema.js
..           json5.js     object.js    repr.js
````

**Comment by andreypopp** [comment]
It shouldn't contain it. What's the issue?

**Comment by vicapow** [comment]
This maybe be a misunderstanding on my part of how .flowconfigs are supposed to work but I was getting this error whenever I tried to integrate the project:

````
node_modules/validated/lib/schema.js.flow:192
192:       return value;
                  ^^^^^ mixed. This type is incompatible with
175: export class ConstantNode<V> extends Node<V> {
                  ^^^^^^^^^^^^ some incompatible instantiation of `V`
````

Looking at `node_modules/validated/lib/schema.js.flow:192`


      // $FlowIssue: not a flow issue really, but we need to propagate type info
      return value;

But when I checked your .flowconfig on github I saw:

    suppress_comment=\\(.\\|\n\\)*\\$FlowIssue

So I figured it must have had to do with the missing .flowconfig in the published npm package.

**Comment by andreypopp** [comment]
Got it. I should of think of a better way to ship typings with the library. In the meantime you can add a suppress_comment config like in validated's .flowconfig.

**Comment by vicapow** [comment]
that solved the issue for me. thanks!

**Comment by andreypopp** [comment]
Ok, 0.8.2 shouldn't require custom `.flowconfig` anymore.
